# 博客标题
navbar:
  blog_title: ""

  # 导航栏菜单，可自行增减，key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值；icon 是 css class，可以省略；增加 name 可以强制显示指定名称
  # Navigation bar menu. `key` is used to associate languages/*.yml. If there is no association, the value of `key` itself will be displayed; if `icon` is a css class, it can be omitted; adding `name` can force the display of the specified name
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }  
    - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }

# 展示 PV 与 UV 统计
footer:
  statistics:
    enable: true
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"
  # 备案号
  beian:
    enable: true
    icp_text: 鲁ICP备2026001211号-1  # ICP备案号
    police_text: 鲁公网安备37112202000287号  # 公安网备案号
    police_code: 37112202000287  # 公安备案编号，用于查询链接

# 暗色模式
dark_mode:
  enable: true
  default: auto

# Slogan(打字机)
index:
  slogan:
    enable: true
    text: 🌊看过大海的人不会忘记海的广阔🌊
    api:
      enable: true
      url: "https://v1.hitokoto.cn/?c=a&c=c&c=d&c=i&c=k&c=l"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]

#---------------------------
# 关于页
# About Page
#---------------------------
about:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  avatar: /img/avatar.png
  name: "Fluid"
  intro: "An elegant theme for Hexo"
  # 更多图标可从 https://hexo.fluid-dev.com/docs/icon/ 查找，`class` 代表图标的 css class，添加 `qrcode` 后，图标不再是链接而是悬浮二维码
  # More icons can be found from https://hexo.fluid-dev.com/docs/en/icon/  `class` is the css class of the icon. If adding `qrcode`, The icon is no longer a link, but a hovering QR code
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/wang551/", tip: "GitHub" }
    - { class: "iconfont icon-mail", link: "https://github.com/wang551/", tip: "GitHub" }   
    # - { class: "iconfont icon-douban-fill", link: "https://douban.com", tip: "豆瓣" }
    # - { class: "iconfont icon-wechat-fill", qrcode: "/img/favicon.png" }

#---------------------------
# 友链页
# Links Page
#---------------------------
links:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  # 友链的成员项
  # Member item of page
  items:
    - {
      title: "张作俊's 窝点",
      intro: "longlong's 窝",
      link: "https://zhangzuojun1127.github.io/",
      # avatar: "/img/favicon.png",
      avatar: "https://zhangzuojun1127.github.io/medias/logo.png"
    }
  default_avatar: /img/avatar.png
